### ISSUE TITLE
fullscreenEventHook Deprecated from xmonad.hs config

### ISSUE THREAD

**Issue by lnhutnam** [arcolinux/arcolinux-xmonad-polybar#2]
I got a issue when update with xmonad version 0.17.0
There is a deprecated function fullscreenEventHook. Can you suggest me to fix this one, thanks sir.
![image](https://user-images.githubusercontent.com/52648432/178131253-876fe7da-f5d2-435d-81f3-3ae288809c93.png)

**Comment by arcolinuxz** [comment]
solved
update your system
